#ifndef RCPU_CHAINPARAMSSEEDS_H
#define RCPU_CHAINPARAMSSEEDS_H
/**
 * List of fixed seed nodes for the RCPU network
 * AUTOGENERATED by contrib/seeds/generate-seeds.py
 *
 * Each line contains a BIP155 serialized (networkID, addr, port) tuple.
 */
// No hardcoded seed nodes. Use DNS seeds or -addnode/-seednode instead.
static const uint8_t chainparams_seed_main[] = {
};
static const uint8_t chainparams_seed_test[] = {
};
static const uint8_t chainparams_seed_signet[] = {
};

#endif // RCPU_CHAINPARAMSSEEDS_H
