# This is a sample rcpu.conf file. Note that a sample bitcoin.conf file will
# be installed as rcpu.conf in the application data directory
# (e.g. %APPDATA%\RCPU on Windows, ~/.rcpu on Linux) on first run.
#
# Please make a copy of this file, and edit it for your needs.
# Lines starting with '#' are comments. Blank lines are ignored.
# See the rcpud help for more information: rcpud --help

# Server mode allows the daemon to accept RPC requests. Comment out by
# default because it is useful to some users.
#server=1

# You must set rpcuser/rpcpassword or use rpcauth to secure the RPC interface.
# Starting rcpud with no rpcuser/rpcpassword will use a cookie file
# (rcpu cookie auth) in the data directory.
#rpcuser=rpcuser
#rpcpassword=hunter2
#rpcauth=rpcuser:9d8d2054e6e6e4f0f2e9d2f...

# How many seconds rcpud will wait for a complete RPC HTTP request.
#rpcclienttimeout=30

# To connect to rcpud with Bitcoin Core-compatible RPC, use:
#  rcpu-cli -rpcport=<port> getblockchaininfo

# Specify the number of connections to the P2P network (default: 8).
#maxconnections=8

# Set database cache size in MiB (4 to 16384, default: 450).
#dbcache=450

# The main network seed nodes:
#addnode=IP:7227