description "RCPU Daemon"

start on runlevel [2345]
stop on starting rc RUNLEVEL=[016]

env RCPUD_BIN="/usr/bin/rcpud"
env RCPUD_USER="rcpu"
env RCPUD_GROUP="rcpu"
env RCPUD_PIDDIR="/var/run/rcpud"
# upstart can't handle variables constructed with other variables
env RCPUD_PIDFILE="/var/run/rcpud/rcpud.pid"
env RCPUD_CONFIGFILE="/etc/rcpu/rcpu.conf"
env RCPUD_DATADIR="/var/lib/rcpud"

expect fork

respawn
respawn limit 5 120
kill timeout 600

pre-start script
    # this will catch non-existent config files
    # rcpud will check and exit with this very warning, but it can do so
    # long after forking, leaving upstart to think everything started fine.
    # since this is a commonly encountered case on install, just check and
    # warn here.
    if ! grep -qs '^rpcpassword=' "$RCPUD_CONFIGFILE" ; then
        echo "ERROR: You must set a secure rpcpassword to run rcpud."
        echo "The setting must appear in $RCPUD_CONFIGFILE"
        echo
        echo "This password is security critical to securing wallets "
        echo "and must not be the same as the rpcuser setting."
        echo "You can generate a suitable random password using the following "
        echo "command from the shell:"
        echo
        echo "bash -c 'tr -dc a-zA-Z0-9 < /dev/urandom | head -c32 && echo'"
        echo
        echo "It is recommended that you also set alertnotify so you are "
        echo "notified of problems:"
        echo
        echo "ie: alertnotify=echo %%s | mail -s \"RCPU Alert\"" \
            "admin@foo.com"
        echo
        exit 1
    fi

    mkdir -p "$RCPUD_PIDDIR"
    chmod 0755 "$RCPUD_PIDDIR"
    chown $RCPUD_USER:$RCPUD_GROUP "$RCPUD_PIDDIR"
    chown $RCPUD_USER:$RCPUD_GROUP "$RCPUD_CONFIGFILE"
    chmod 0660 "$RCPUD_CONFIGFILE"
end script

exec start-stop-daemon \
    --start \
    --pidfile "$RCPUD_PIDFILE" \
    --chuid $RCPUD_USER:$RCPUD_GROUP \
    --exec "$RCPUD_BIN" \
    -- \
    -pid="$RCPUD_PIDFILE" \
    -conf="$RCPUD_CONFIGFILE" \
    -datadir="$RCPUD_DATADIR" \
    -disablewallet \
    -daemon

