#!/usr/bin/env bash
#
#  rcpud The RCPU server.
#
#
# chkconfig: 345 80 20
# description: rcpud
# processname: rcpud
#

# Source function library.
. /etc/init.d/functions

# you can override defaults in /etc/sysconfig/rcpud, see below
if [ -f /etc/sysconfig/rcpud ]; then
        . /etc/sysconfig/rcpud
fi

RETVAL=0

prog=rcpud
# you can override the lockfile via RCPUD_LOCKFILE in /etc/sysconfig/rcpud
lockfile=${RCPUD_LOCKFILE-/var/lock/subsys/rcpud}

# rcpud defaults to /usr/bin/rcpud, override with RCPUD_BIN
rcpud=${RCPUD_BIN-/usr/bin/rcpud}

# rcpud opts default to -disablewallet, override with RCPUD_OPTS
rcpud_opts=${RCPUD_OPTS--disablewallet}

start() {
    echo -n $"Starting $prog: "
    daemon $DAEMONOPTS $rcpud $rcpud_opts
    RETVAL=$?
    echo
    [ $RETVAL -eq 0 ] && touch $lockfile
    return $RETVAL
}

stop() {
    echo -n $"Stopping $prog: "
    killproc $prog -t600
    RETVAL=$?
    echo
    [ $RETVAL -eq 0 ] && rm -f $lockfile
    return $RETVAL
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    status)
        status $prog
        ;;
    restart)
        stop
        start
        ;;
    *)
        echo "Usage: service $prog {start|stop|status|restart}"
        exit 1
        ;;
esac
